# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analysis.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

import spec_pb2 as spec__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name='analysis.proto',
    package='cabe.proto',
    syntax='proto3',
    serialized_pb=_b(
        '\n\x0e\x61nalysis.proto\x12\ncabe.proto\x1a\nspec.proto\"%\n\x10\x41nalysisMetadata\x12\x11\n\treport_id\x18\x01 \x01(\t\"\xbb\x01\n\x0e\x41nalysisResult\x12\x11\n\tresult_id\x18\x01 \x01(\t\x12\x33\n\x0f\x65xperiment_spec\x18\x02 \x01(\x0b\x32\x1a.cabe.proto.ExperimentSpec\x12\x37\n\x11\x61nalysis_metadata\x18\x03 \x01(\x0b\x32\x1c.cabe.proto.AnalysisMetadata\x12(\n\tstatistic\x18\x04 \x01(\x0b\x32\x15.cabe.proto.Statistic\"\xa0\x01\n\tStatistic\x12\r\n\x05lower\x18\x01 \x01(\x01\x12\r\n\x05upper\x18\x02 \x01(\x01\x12\x0f\n\x07p_value\x18\x03 \x01(\x01\x12\x1a\n\x12significance_level\x18\x04 \x01(\x01\x12\x16\n\x0epoint_estimate\x18\x06 \x01(\x01\x12\x16\n\x0e\x63ontrol_median\x18\x07 \x01(\x01\x12\x18\n\x10treatment_median\x18\x08 \x01(\x01\x42!Z\x1fgo.skia.org/infra/cabe/go/protob\x06proto3'
    ),
    dependencies=[
        spec__pb2.DESCRIPTOR,
    ])

_ANALYSISMETADATA = _descriptor.Descriptor(
    name='AnalysisMetadata',
    full_name='cabe.proto.AnalysisMetadata',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='report_id',
            full_name='cabe.proto.AnalysisMetadata.report_id',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=42,
    serialized_end=79,
)

_ANALYSISRESULT = _descriptor.Descriptor(
    name='AnalysisResult',
    full_name='cabe.proto.AnalysisResult',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='result_id',
            full_name='cabe.proto.AnalysisResult.result_id',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='experiment_spec',
            full_name='cabe.proto.AnalysisResult.experiment_spec',
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='analysis_metadata',
            full_name='cabe.proto.AnalysisResult.analysis_metadata',
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='statistic',
            full_name='cabe.proto.AnalysisResult.statistic',
            index=3,
            number=4,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=82,
    serialized_end=269,
)

_STATISTIC = _descriptor.Descriptor(
    name='Statistic',
    full_name='cabe.proto.Statistic',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='lower',
            full_name='cabe.proto.Statistic.lower',
            index=0,
            number=1,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='upper',
            full_name='cabe.proto.Statistic.upper',
            index=1,
            number=2,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='p_value',
            full_name='cabe.proto.Statistic.p_value',
            index=2,
            number=3,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='significance_level',
            full_name='cabe.proto.Statistic.significance_level',
            index=3,
            number=4,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='point_estimate',
            full_name='cabe.proto.Statistic.point_estimate',
            index=4,
            number=6,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='control_median',
            full_name='cabe.proto.Statistic.control_median',
            index=5,
            number=7,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='treatment_median',
            full_name='cabe.proto.Statistic.treatment_median',
            index=6,
            number=8,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=272,
    serialized_end=432,
)

_ANALYSISRESULT.fields_by_name[
    'experiment_spec'].message_type = spec__pb2._EXPERIMENTSPEC
_ANALYSISRESULT.fields_by_name[
    'analysis_metadata'].message_type = _ANALYSISMETADATA
_ANALYSISRESULT.fields_by_name['statistic'].message_type = _STATISTIC
DESCRIPTOR.message_types_by_name['AnalysisMetadata'] = _ANALYSISMETADATA
DESCRIPTOR.message_types_by_name['AnalysisResult'] = _ANALYSISRESULT
DESCRIPTOR.message_types_by_name['Statistic'] = _STATISTIC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnalysisMetadata = _reflection.GeneratedProtocolMessageType(
    'AnalysisMetadata',
    (_message.Message,),
    dict(
        DESCRIPTOR=_ANALYSISMETADATA,
        __module__='analysis_pb2'
        # @@protoc_insertion_point(class_scope:cabe.proto.AnalysisMetadata)
    ))
_sym_db.RegisterMessage(AnalysisMetadata)

AnalysisResult = _reflection.GeneratedProtocolMessageType(
    'AnalysisResult',
    (_message.Message,),
    dict(
        DESCRIPTOR=_ANALYSISRESULT,
        __module__='analysis_pb2'
        # @@protoc_insertion_point(class_scope:cabe.proto.AnalysisResult)
    ))
_sym_db.RegisterMessage(AnalysisResult)

Statistic = _reflection.GeneratedProtocolMessageType(
    'Statistic',
    (_message.Message,),
    dict(
        DESCRIPTOR=_STATISTIC,
        __module__='analysis_pb2'
        # @@protoc_insertion_point(class_scope:cabe.proto.Statistic)
    ))
_sym_db.RegisterMessage(Statistic)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(
    descriptor_pb2.FileOptions(), _b('Z\037go.skia.org/infra/cabe/go/proto'))
# @@protoc_insertion_point(module_scope)
