# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analysis.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import spec_pb2 as spec__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalysis.proto\x12\ncabe.proto\x1a\nspec.proto\"%\n\x10\x41nalysisMetadata\x12\x11\n\treport_id\x18\x01 \x01(\t\"\xbb\x01\n\x0e\x41nalysisResult\x12\x11\n\tresult_id\x18\x01 \x01(\t\x12\x33\n\x0f\x65xperiment_spec\x18\x02 \x01(\x0b\x32\x1a.cabe.proto.ExperimentSpec\x12\x37\n\x11\x61nalysis_metadata\x18\x03 \x01(\x0b\x32\x1c.cabe.proto.AnalysisMetadata\x12(\n\tstatistic\x18\x04 \x01(\x0b\x32\x15.cabe.proto.Statistic\"\xa0\x01\n\tStatistic\x12\r\n\x05lower\x18\x01 \x01(\x01\x12\r\n\x05upper\x18\x02 \x01(\x01\x12\x0f\n\x07p_value\x18\x03 \x01(\x01\x12\x1a\n\x12significance_level\x18\x04 \x01(\x01\x12\x16\n\x0epoint_estimate\x18\x06 \x01(\x01\x12\x16\n\x0e\x63ontrol_median\x18\x07 \x01(\x01\x12\x18\n\x10treatment_median\x18\x08 \x01(\x01\x42!Z\x1fgo.skia.org/infra/cabe/go/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\037go.skia.org/infra/cabe/go/proto'
  _globals['_ANALYSISMETADATA']._serialized_start=42
  _globals['_ANALYSISMETADATA']._serialized_end=79
  _globals['_ANALYSISRESULT']._serialized_start=82
  _globals['_ANALYSISRESULT']._serialized_end=269
  _globals['_STATISTIC']._serialized_start=272
  _globals['_STATISTIC']._serialized_end=432
# @@protoc_insertion_point(module_scope)
