# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spec.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nspec.proto\x12\ncabe.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x01\n\tBuildSpec\x12\x31\n\x0egitiles_commit\x18\x01 \x01(\x0b\x32\x19.cabe.proto.GitilesCommit\x12\x30\n\x0egerrit_changes\x18\x02 \x03(\x0b\x32\x18.cabe.proto.GerritChange\x12\x37\n\x11installed_browser\x18\x03 \x01(\x0b\x32\x1c.cabe.proto.InstalledBrowser\"f\n\x0cGerritChange\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0f\n\x07project\x18\x02 \x01(\t\x12\x0e\n\x06\x63hange\x18\x03 \x01(\x03\x12\x10\n\x08patchset\x18\x04 \x01(\x03\x12\x15\n\rpatchset_hash\x18\x05 \x01(\t\"Y\n\rGitilesCommit\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0f\n\x07project\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12\x0b\n\x03ref\x18\x04 \x01(\t\x12\x10\n\x08position\x18\x05 \x01(\r\"1\n\x10InstalledBrowser\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"m\n\x0b\x46inchConfig\x12\x11\n\tseed_hash\x18\x01 \x01(\t\x12\x17\n\x0fseed_changelist\x18\x02 \x01(\x04\x12\x32\n\x0eseed_timestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"d\n\x07RunSpec\x12\n\n\x02os\x18\x01 \x01(\t\x12\x1e\n\x16synthetic_product_name\x18\x02 \x01(\t\x12-\n\x0c\x66inch_config\x18\x03 \x01(\x0b\x32\x17.cabe.proto.FinchConfig\"8\n\x0c\x41nalysisSpec\x12(\n\tbenchmark\x18\x01 \x03(\x0b\x32\x15.cabe.proto.Benchmark\"+\n\tBenchmark\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08workload\x18\x02 \x03(\t\"[\n\x07\x41rmSpec\x12)\n\nbuild_spec\x18\x01 \x03(\x0b\x32\x15.cabe.proto.BuildSpec\x12%\n\x08run_spec\x18\x02 \x03(\x0b\x32\x13.cabe.proto.RunSpec\"\xaf\x01\n\x0e\x45xperimentSpec\x12#\n\x06\x63ommon\x18\x01 \x01(\x0b\x32\x13.cabe.proto.ArmSpec\x12$\n\x07\x63ontrol\x18\x02 \x01(\x0b\x32\x13.cabe.proto.ArmSpec\x12&\n\ttreatment\x18\x03 \x01(\x0b\x32\x13.cabe.proto.ArmSpec\x12*\n\x08\x61nalysis\x18\x04 \x01(\x0b\x32\x18.cabe.proto.AnalysisSpecB!Z\x1fgo.skia.org/infra/cabe/go/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spec_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\037go.skia.org/infra/cabe/go/proto'
  _globals['_BUILDSPEC']._serialized_start=60
  _globals['_BUILDSPEC']._serialized_end=229
  _globals['_GERRITCHANGE']._serialized_start=231
  _globals['_GERRITCHANGE']._serialized_end=333
  _globals['_GITILESCOMMIT']._serialized_start=335
  _globals['_GITILESCOMMIT']._serialized_end=424
  _globals['_INSTALLEDBROWSER']._serialized_start=426
  _globals['_INSTALLEDBROWSER']._serialized_end=475
  _globals['_FINCHCONFIG']._serialized_start=477
  _globals['_FINCHCONFIG']._serialized_end=586
  _globals['_RUNSPEC']._serialized_start=588
  _globals['_RUNSPEC']._serialized_end=688
  _globals['_ANALYSISSPEC']._serialized_start=690
  _globals['_ANALYSISSPEC']._serialized_end=746
  _globals['_BENCHMARK']._serialized_start=748
  _globals['_BENCHMARK']._serialized_end=791
  _globals['_ARMSPEC']._serialized_start=793
  _globals['_ARMSPEC']._serialized_end=884
  _globals['_EXPERIMENTSPEC']._serialized_start=887
  _globals['_EXPERIMENTSPEC']._serialized_end=1062
# @@protoc_insertion_point(module_scope)
