# Copyright 2015 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /base
  static_dir: trace_viewer/base
  secure: always

- url: /core
  static_dir: trace_viewer/core
  secure: always

- url: /extras
  static_dir: trace_viewer/extras
  secure: always

- url: /components
  static_dir: third_party/components
  secure: always

- url: /trace_viewer
  static_dir: trace_viewer
  secure: always

- url: /gl-matrix-min.js
  static_files: third_party/gl-matrix/dist/gl-matrix-min.js
  upload: third_party/gl-matrix/dist/gl-matrix-min.js
  secure: always

- url: /jszip.min.js
  static_files: third_party/jszip/jszip.min.js
  upload: third_party/jszip/jszip.min.js
  secure: always

- url: /d3.min.js
  static_files: third_party/d3/d3.min.js
  upload: third_party/d3/d3.min.js
  secure: always

- url: /.*
  static_files: trace_viewer/extras/drive/index.html
  upload: trace_viewer/extras/drive/index.html
  secure: always
