#!/usr/bin/env python
# Copyright (c) 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import sys

from hooks import install
from tracing.build import tracing_dev_server

if __name__ == '__main__':
  install.InstallHooks()
  sys.exit(tracing_dev_server.Main(sys.argv[1:]))
