#!/usr/bin/env python
# Copyright (c) 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import sys

import trace_viewer # Brings in tvcm bindings.
from tvcm import test_runner
import tvcm


if __name__ == '__main__':
  runner = test_runner.TestRunner()
  runner.AddModule(tvcm)
  runner.AddModule(trace_viewer)
  sys.exit(runner.Main())
