#!/usr/bin/env python
# Copyright (c) 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import sys

from trace_viewer.build import vulcanize_trace_viewer


if __name__ == '__main__':
  sys.exit(vulcanize_trace_viewer.Main(sys.argv[1:]))
