// Copyright (c) 2013 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

'use strict';

var g_picture_trace = {
  'cat': 'disabled-by-default-cc.debug',
  'pid': 23969,
  'tid': 1799,
  'ts': 1427012847340,
  'ph': 'O',
  'name': 'cc::Picture',
  'args': {
    'snapshot': {
      'params': {
        'layer_rect': [
          557,
          194,
          33,
          31
        ],
        'opaque_rect': [
          0,
          0,
          0,
          0
        ]
      },
      'skp64': 'AQAAAJABAACQAAAAIQAAAB8AAACQAQAAkAAAAAAAAAAAAAAACwAAACEAAAAfAAAAAwAAAAFkYWVyTAEAAAgAAB4DAAAACAAAHgMAAAAMAAAjAADIwwAAEMMcAAADAADIQwAAEEMAgNhDAAAvQwEAAABEAQAAGAAAFQEAAAAAAMhDAAAQQwCA2EMAAC9DDAAAIwAAAAAAAAAADAAAIwAAAAAAAAAAGAAAFQIAAAAAAMhDAAAQQwCA2EMAAC9DGAAAFQIAAAAAAMhDAAAQQwCA2EMAAC9DCAAAHgMAAAAcAAADAADQQwAAIEMAgAFEAAAxQwEAAADUAAAAGAAAFQMAAAAAANBDAAAgQwCAAUQAADFDBAAAHGwAABQEAAAAGgAAADMASwBMAE8ATABTAAMANQBSAEoASABVAFYAAAANAAAAANYdQwAGNEMAAC5DAADQQwCA1UMAgNpDAIDcQwCA3kMAgOBDAIDlQwAA50MAAO1DAADyQwAA90MAgPtDAID+QwQAABwEAAAcdGNhZgIAAAAPU2tDbGVhclhmZXJtb2RlDVNrU3JjWGZlcm1vZGVjZnB0AQAAAAEBBUFyaWFsBApBcmlhbCBCb2xkBgxBcmlhbC1Cb2xkTVT+\/wAAeWFyYfQAAAAgdG5wBAAAAAAAQEEAAIA\/AAAAAAAAgD8AAAAAAACAQAAAAP8CMAAAAAAAAAAAAAAAAAAAAQAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQQAAgD8AAAAAAACAPwAAAAAAAIBA\/\/\/\/\/wIwAQAAAAAAAAAAAAAAAAACAAAABAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBBAACAPwAAAAAAAIA\/AAAAAAAAgED+uYKZADABAAAAAAAAAIBBAACAPwAAAAAAAIA\/AAAAAAAAgEAzMzP\/ARCBAAMAAAABAAAAIGZvZQ==' // @suppress longLineCheck
    }
  },
  'id': '0x7d229bc0'
};
