#!/usr/bin/env python
# Copyright (c) 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import argparse
import os
import sys

hooks_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if hooks_path not in sys.path:
  sys.path.append(hooks_path)

from hooks import install

import tracing # Brings in tvcm bindings.
from tvcm import test_runner
import tvcm
import vinn


if __name__ == '__main__':
  parser = argparse.ArgumentParser(
      description='Run python tests.')
  parser.add_argument(
    '--no-install-hooks', dest='install_hooks', action='store_false')
  parser.set_defaults(install_hooks=True)
  args = parser.parse_args()
  if args.install_hooks:
    install.InstallHooks()

  runner = test_runner.TestRunner()
  runner.AddModule(tvcm)
  runner.AddModule(vinn)
  runner.AddModule(tracing)
  sys.exit(runner.Main())
