#!/usr/bin/env python
# Copyright (c) 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import sys
import os

hooks_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if hooks_path not in sys.path:
  sys.path.append(hooks_path)

from hooks import install

import tracing # Brings in tvcm bindings.
from tvcm import test_runner
import tvcm


if __name__ == '__main__':
  install.InstallHooks()

  runner = test_runner.TestRunner()
  runner.AddModule(tvcm)
  runner.AddModule(tracing)
  sys.exit(runner.Main())
