#!/usr/bin/env python
# Copyright (c) 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import sys
import os

from build import trace2html

if __name__ == '__main__':
  sys.exit(trace2html.Main(sys.argv[1:]))
