#!/usr/bin/env python
# Copyright 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from telemetry import decorators
from telemetry.internal.util import find_dependencies


@decorators.Deprecated(2015, 11, 23, 'Please use tools/perf/find_dependencies.')
def main():
  find_dependencies.FindDependenciesCommand.main()


if __name__ == '__main__':
  main()
