#!/usr/bin/env python
# Copyright (c) 2012 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import os
import sys

from telemetry.unittest import gtest_progress_reporter
from telemetry.unittest import run_tests


if __name__ == '__main__':
  base_dir = os.path.dirname(os.path.realpath(__file__))
  progress_reporters = [
      gtest_progress_reporter.GTestProgressReporter(sys.stdout)]
  run_tests.config = run_tests.Config(base_dir, [base_dir], progress_reporters)
  sys.exit(run_tests.RunTestsCommand.main())
