#!/usr/bin/env python
# Copyright (c) 2012 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import os
import sys
import subprocess


if __name__ == '__main__':
  telemetry_dir = os.path.dirname(os.path.realpath(__file__))

  env = os.environ.copy()
  if 'PYTHONPATH' in env:
    env['PYTHONPATH'] = env['PYTHONPATH'] + os.pathsep + telemetry_dir
  else:
    env['PYTHONPATH'] = telemetry_dir

  path_to_run_tests = os.path.join(telemetry_dir, 'telemetry', 'unittest_util',
                                   'run_tests.py')
  argv = ['--top-level-dir', telemetry_dir] + sys.argv[1:]
  sys.exit(subprocess.call([sys.executable, path_to_run_tests] + argv, env=env))
