#!/usr/bin/env python
# Copyright (c) 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import os
import sys

if __name__ == '__main__':
  # This pre-commit hook was replaced by a pre-submit hook (see PRESUBMIT.py).
  sys.exit(0)

  f = __file__
  if os.path.islink(f):
    f = os.path.abspath(os.path.join(os.path.dirname(f), os.readlink(f)))
  top_dir = os.path.abspath(os.path.join(os.path.dirname(f), '..'))
  sys.path.append(top_dir)
  from hooks import pre_commit
  sys.exit(pre_commit.Main(sys.argv[1:]))
