#!/usr/bin/env python
# Copyright (c) 2015 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import os
import sys


if __name__ == '__main__':
  from perf_insights import map_traces_locally
  sys.exit(map_traces_locally.Main(sys.argv[1:]))
