#!/usr/bin/env python
# Copyright (c) 2015 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# TODO(anniesullie): Remove this file when the test recipes are updated.

import os
import sys

if __name__ == '__main__':
  from perf_insights_build import run_py_tests
  sys.exit(run_py_tests.Main(sys.argv))
